### ISSUE TITLE
Date of photos does not appear correctly

### ISSUE THREAD

**Issue by aviv926** [MaxiHuHe04/iTunes-Backup-Explorer#28]
I want to say thanks again for this amazing extension!
There is something I noticed that when I export any photo the original date the photo was taken does not appear
and instead the date the backup was taken appears
Even in the EXIF of the photo, the original date does not appear

Do you know how to fix it?
Thank you for your wonderful work

**Comment by MaxiHuHe04** [comment]
Hey @aviv926,
that's interesting. This should have been fixed in v1.3 by the commit https://github.com/MaxiHuHe04/iTunes-Backup-Explorer/commit/b450c64d45a6b790451a94751cc08757f32e0b6e.
Could you please provide the following information?
- Your operating system
- iTunes Backup Explorer version
- Device and iOS version
- The folder path you extracted the photos from

Are you sure the photos have the right date on the phone itself? Normally, this program should not change any EXIF data in the extraction process.

**Comment by aviv926** [comment]
> Hey

Thanks for your response @MaxiHuHe04 , here is more info about the problem:

My operating system is Windows 10
iTunes Backup Explorer latest version - 1.4
Device and iOS version - iPhone 11, ios 16.1
Non-encrypted backup

I have now retested with version 1.4 and I am experiencing the same problem, the images arrive without their original EXIF the images were extracted from:
MEDIA/DCIM/.MISC/100APPLE
I tried a picture in JPG format and in addition, also a video in MOV format
This is the EXIF data that I got using exiftool on these files

![image](https://github.com/MaxiHuHe04/iTunes-Backup-Explorer/assets/51673860/023dfca2-f939-419a-9fe4-ae42e90d846c)


In order to check that there is no problem with my backup, I used [iBackupViewerSetup](https://www.imactools.com/iphonebackupviewer/)

on the same photos, and I was able to get the correct EXIF details

**Comment by MaxiHuHe04** [comment]
Have you tried extracting photos from `Media/DCIM/100APPLE`? I think the images in `Media/DCIM/.MISC/100APPLE` are not the original ones but thumbnails or something like that. The resolution of 900x1600 also doesn't seem right. The backup of my phone doesn't even have any files in `.MISC`.

**Comment by aviv926** [comment]
Thanks for your response @MaxiHuHe04

Sorry, this is my mistake, the picture is not in Media/DCIM/.MISC/100APPLE, there is really nothing in it.
These are the meaning in the previous response that the images I checked are in Media/DCIM/100APPLE

But the situation is still the same and the photos are exported without their original EXIF

And again when I tried to export with iBackupViewerSetup I was able to get the original EXIF of the photos, I will put a comparison here
iBackupViewerSetup vs. iTunes Backup Explorer

**Exif from iBackupViewerSetup extract**
![image](https://github.com/MaxiHuHe04/iTunes-Backup-Explorer/assets/51673860/72ec44aa-5973-45cb-bcc6-5849826c6fff)

**Exif from iTunes Backup Explorer 1.4 extract**
![image](https://github.com/MaxiHuHe04/iTunes-Backup-Explorer/assets/51673860/3e1522e8-53cf-4813-941a-eeedb8e18b9e)

**Comment by MaxiHuHe04** [comment]
My guess is that maybe you edited that photo on January 1st. Could that be the reason for the different dates? Then iBackupViewer apparently takes the capture date of the EXIF data of the photos which would be November 15th.
Currently, my program just uses the last modified date of the original files in the backup database for the extracted ones. It doesn't interact with or change any EXIF data. This could change when a separate photo viewer feature were added at some point.
Actually, neither of the screenshots you posted show any EXIF data. Those dates are just Windows file system attributes. `DateTimeOriginal`, location, device or camera settings like ISO, shutter speed, etc. would be EXIF tags.

**Comment by MaxiHuHe04** [comment]
Could you please check whether there is any difference in the content of the extracted files by typing in
`Get-FileHash .\iBackupViewerSetup.PNG ".\iTunes Backup Explorer.PNG"`?

**Comment by aviv926** [comment]
I was able to figure out what the problem was
When I export photos that were taken from the phone's camera, everything is exported correctly, including the EXIF

But when I export WhatsApp photos/photos sent to the device, their EXIF is removed (for an unknown reason)

It happens with all the types of extensions I tested

For example, if I export a photo/video taken through the iPhone's camera, both through iTunes Backup Explorer 1.4 and through iBackupViewer, the EXIF appears correctly

But if I export a screenshot or a picture that is through WhatsApp, the EXIF does not come out properly through iTunes Backup Explorer 1.4, but the EXIF does come out properly through iBackupViewer

for example this is a Exif of an image from Whatsapp:
![image](https://github.com/MaxiHuHe04/iTunes-Backup-Explorer/assets/51673860/25d4ecc1-c266-48e6-a08e-45998570e0f0)

this is the Get-FileHash:
![image](https://github.com/MaxiHuHe04/iTunes-Backup-Explorer/assets/51673860/295743a8-6be9-40b6-8a59-b3c5130ea255)

**Comment by MaxiHuHe04** [comment]
Alright, that makes sense. WhatsApp removes EXIF data probably for privacy reasons and/or maximum compression.
And again, these screenshots still don't show any real EXIF data in both of them. The files themselves are identical as Get-FileHash shows.
The only difference is that iBackupViewer sets the File Modification and Creation date file system attributes to other values. It probably uses the file `Birth` date instead of `LastModified`.

**Comment by aviv926** [comment]
> Alright, that makes sense. WhatsApp removes EXIF data probably for privacy reasons and/or maximum compression. And again, these screenshots still don't show any real EXIF data in both of them. The files themselves are identical as Get-FileHash shows. The only difference is that iBackupViewer sets the File Modification and Creation date file system attributes to other values. It probably uses the file `Birth` date instead of `LastModified`.

It sounds like it's really like that because the date that iBackupViewer sets on the image is really the date the image was received on the device (I verified it by viewing the date of the original image as sent via WhatsApp) as you can see in the image I attached
![image](https://github.com/MaxiHuHe04/iTunes-Backup-Explorer/assets/51673860/e4e9dc94-7a10-41aa-996d-0cd4f8b16939)



This is something that can be added to iTunes Backup Explorer because it can be really good for keeping the original appearance order of the photos

I would love to know what you think
